# Generated by Django 6.1 on 2026-08-28 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('python', 'Python'), ('sql', 'SQL')], max_length=10)),
                ('prompt', models.TextField(help_text='The problem statement shown to students')),
                ('reference_solution', models.TextField(help_text='Correct solution code used for reference')),
                ('marks', models.PositiveIntegerField(default=10)),
                ('sql_setup_script', models.TextField(blank=True, help_text='SQL to create/seed tables (SQL questions only)', null=True)),
                ('sql_reference_query', models.TextField(blank=True, help_text='Correct SQL query (SQL questions only)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, help_text='Input passed to the program (stdin)')),
                ('expected_output', models.TextField(help_text='Expected output to match against')),
                ('is_hidden', models.BooleanField(default=False, help_text="Hide this test case's details from students")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='questions.question')),
            ],
        ),
    ]
