# Generated by Django 6.1 on 2026-08-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='stream',
        ),
        migrations.AddField(
            model_name='candidate',
            name='degree',
            field=models.CharField(default='B.E.', help_text='Select a common degree or type your own', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution',
            field=models.CharField(default='IFET College of Engineering', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='program_level',
            field=models.CharField(choices=[('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)')], default='UG', max_length=2),
        ),
    ]
